include:
  - docker-compose-infrastructure.yml
services:
#  # ============ACCOUNT==========
#  account:
#    build:
#      context: .
#      dockerfile: account/Dockerfile
#    container_name: account
#    ports:
#      - "8088:8088"
#    environment:
#      # Spring Boot
#      SPRING_PROFILES_ACTIVE: prod
#      SERVER_PORT: 8088
#
#      # Eureka
#      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka:8761/eureka/
#      EUREKA_CLIENT_REGISTER_WITH_EUREKA: true
#      EUREKA_CLIENT_FETCH_REGISTRY: true
#
#      # PostgresSQL (Account DB)
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/account_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
#      # Kafka
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092
#
#      # Redis
#      SPRING_DATA_REDIS_HOST: redis
#      SPRING_DATA_REDIS_PORT: 6379
#    networks:
#      - microservices-net

  redis:
    image: redis:7.0.12
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "redis" ]
    ports:
      - "6379:6379"
    networks:
      - microservices-net

  mongodb:
    image: mongo:4.4.24
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: appdatabase
    networks:
      - microservices-net

  # ============GATEWAY===============
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://eureka:8761/eureka/
    depends_on:
      - eureka
    networks:
      - microservices-net
      - keycloak-net
  # =================== KEYCLOAK ===================
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4.1

    command: start-dev
    # command: start --optimized для продакшн
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DB_TITLE}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: auth.reybo.ru
      KC_HOSTNAME_STRICT: "true"
      KC_HTTP_PORT: 8080
      KC_HTTP_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY: edge
      KC_PROXY_HEADERS: xforwarded
      # ========= Настройка пулов ===========
      KC_DB_POOL_INITIAL_SIZE: "5"
      KC_DB_POOL_MIN_SIZE: "5"
      KC_DB_POOL_MAX_SIZE: "10"
      # ========= Настройка JAVA ===========
      JAVA_OPTS_KC_HEAP: "-XX:MaxRAMPercentage=70"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
    networks:
      - keycloak-net
  # =================== /KEYCLOAK ===================

#  # ============SHOP===============
#  shop:
#    container_name: shop
#    build:
#      context: .
#      dockerfile: shop/Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      # OPEN FEIGN
#      - FEIGN_CLIENTS_AUTH_SERVICE_NAME=auth
#      - FEIGN_CLIENTS_AUTH_SERVICE_URL=http://auth:8081
#      - FEIGN_CLIENTS_ACCOUNT_SERVICE_NAME=account
#      - FEIGN_CLIENTS_ACCOUNT_SERVICE_URL=http://account:8088
#      - SPRING_PROFILES_ACTIVE=prod
#      - POSTGRES_URL=jdbc:postgresql://postgres:5432/shop_db
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USERNAME=postgres
#      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://eureka:8761/eureka/
#      - HIBERNATE_DDL_AUTO_MODE=create
#      - HIBERNATE_SHOW_SQL=true
#      - LIQUIBASE_ENABLED=false
#      - LIQUIBASE_DEFAULT_DB_SCHEMA=frontend_schema
#    depends_on:
#      - eureka
#      - postgres
#    networks:
#      - microservices-net

#  # ============CRM===============
#  crm:
#    container_name: crm
#    build:
#      context: .
#      dockerfile: crm/Dockerfile
#    ports:
#      - "8082:8082"
#    environment:
#      - POSTGRES_URL=jdbc:postgresql://postgres:5432/crm_db
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USERNAME=postgres
#      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://eureka:8761/eureka/
#      - HIBERNATE_DDL_AUTO_MODE=create
#      - LIQUIBASE_ENABLED=false
#      - LIQUIBASE_DEFAULT_DB_SCHEMA=crm_schema
#    depends_on:
#      - eureka
#      - postgres
#    networks:
#      - microservices-net

networks:
  microservices-net:
  keycloak-net:
