services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4.1
    command: start-dev
#    command: start --optimized для продакшн
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DB_TITLE}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: http://localhost:8091
      KC_HTTP_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # ========= Настройка пулов ===========
      KC_DB_POOL_INITIAL_SIZE: "5"
      KC_DB_POOL_MIN_SIZE: "5"
      KC_DB_POOL_MAX_SIZE: "10"
      # ========= Настройка JAVA ===========
      JAVA_OPTS_KC_HEAP: "-XX:MaxRAMPercentage=70"
    ports:
      - "8091:8080"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
    networks:
      - keycloack-net
networks:
  keycloack-net:
volumes:
  pgdata: