spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: ${KEYCLOAK_CLIENT_SECRET_OF_GATEWAY}
            scope:
              - openid
              - profile
              - email
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: "https://api.reybo.ru/login/oauth2/code/gateway"

        provider:
          keycloak:
            issuer-uri: https://auth.reybo.ru/realms/shop
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: https://auth.reybo.ru/realms/shop

  cloud:
    gateway:
      routes:
        - id: frontend-crm
          uri: http://frontend-crm:3000
          predicates:
            - Host=crm.reybo.ru
          filters:
            - TokenRelay=
        - id: frontend-shop
          uri: http://frontend-shop:3000
          predicates:
            - Host=reybo.ru
          filters:
            - TokenRelay=

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}

server:
  port: 8765
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        domain: reybo.ru
        secure: true
        same-site: lax

logging:
  level:
    # Основное логирование OAuth2 и Security
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.client.web: DEBUG
    org.springframework.security.oauth2.client.web.server: DEBUG
    org.springframework.security.oauth2.client.registration: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.web.server: DEBUG
    org.springframework.security.web.server.authentication: DEBUG
    org.springframework.web.server: DEBUG
    org.springframework.web.reactive.function.client: TRACE
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.http.codec.json: DEBUG

    # Логирование ошибок
    org.springframework.boot.autoconfigure.security: DEBUG
    reactor.netty.http.client: DEBUG

    # Ваш пакет
    com.reybo.gateway: DEBUG

    # Отключить лишнее (опционально)
    org.hibernate: WARN
    org.springframework.cloud.commons: INFO