spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: ${KEYCLOAK_CLIENT_SECRET_OF_GATEWAY}
            scope:
              - openid
              - profile
              - email
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: "https://api.reybo.ru/login/oauth2/code/gateway"

        provider:
          keycloak:
            issuer-uri: https://auth.reybo.ru/realms/shop
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: https://auth.reybo.ru/realms/shop

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: keycloak-proxy
              uri: http://keycloak:8080
              predicates:
                - Path=/realms/**, /resources/**

            - id: keycloak-resources
              uri: http://keycloak:8080
              predicates:
                - Path=/resources/**
              filters:
                - StripPrefix=0

            - id: shop-service
              uri: lb://shop
              predicates:
                - Path=/api/v1/shop/**
              filters:
                - TokenRelay=

            - id: crm-web-app
              uri: lb://crm
              predicates:
                - Path=/api/v1/crm/**
              filters:
                - TokenRelay=

            - id: account
              uri: lb://account
              predicates:
                - Path=/api/v1/account/**
              filters:
                - TokenRelay=

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}

server:
  port: 8765
  forward-headers-strategy: native
  error:
    include-message: always
    include-binding-errors: always