server {
    listen 80;
    server_name reybo.ru api.reybo.ru auth.reybo.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name reybo.ru api.reybo.ru;

   ssl_certificate /etc/letsencrypt/live/reybo.ru/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/reybo.ru/privkey.pem;

    location / {
        proxy_pass http://localhost:8765;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name auth.reybo.ru;

   ssl_certificate /etc/letsencrypt/live/reybo.ru/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/reybo.ru/privkey.pem;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}




