name: Docker build CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    environment: backend_env
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Create .env file from secret
      run: echo "${{ secrets.BACKEND_ENV }}" > .env
      
    - name: Build and run backend
      run: docker compose -f docker-compose-build.yml up -d --build
